### Cargamos librerias, dataframe y limpio filas

In [3]:
import pandas as pd
import numpy as np
import statsmodels.api as sm

!pip install pyreadstat
import pyreadstat
file_path = 'BASEDATOS_ARGENTINA_122_ .sav'


df_diputados, meta = pyreadstat.read_sav(file_path)

df_diputados = df_diputados.loc[~((df_diputados['ID101'] == 98) | (df_diputados['ID101'] == 99) | 
                                   (df_diputados['PRO102'] == 98) | (df_diputados['PRO112'] == 99))]

### Investigamos un poco el dataframe

In [5]:
df_diputados.info()

<class 'pandas.core.frame.DataFrame'>
Index: 110 entries, 0 to 110
Columns: 266 entries, Encuestado to peso
dtypes: float64(261), object(5)
memory usage: 229.5+ KB


In [7]:
df_diputados.head()

Encuestado  País   legis  partido  departa  tipoelec  comision01  \
0         4.0   1.0  2022.0     20.0     12.0       2.0         7.0   
1         6.0   1.0  2022.0      7.0      2.0       2.0         2.0   
2        10.0   1.0  2022.0      2.0     15.0       2.0         1.0   
3        11.0   1.0  2022.0      7.0      2.0       2.0         5.0   
4        12.0   1.0  2022.0     29.0      9.0       2.0        37.0   

   comision02  comision03  comision04  ...  pcontacto2  pcontacto3  \
0        16.0        31.0         NaN  ...         NaN         NaN   
1         3.0        15.0        25.0  ...         NaN         NaN   
2         2.0         3.0         4.0  ...         NaN         NaN   
3        15.0        27.0        35.0  ...         NaN         NaN   
4        38.0         NaN         NaN  ...         NaN         NaN   

   resultado1  resultado107  causaneg1  resultado2  causaneg2  resultado3  \
0         1.0                      NaN         NaN        NaN         NaN   
1         1.0                      NaN         NaN        NaN         NaN   
2         1.0                      NaN         NaN        NaN         NaN   
3         1.0                      NaN         NaN        NaN         NaN   
4         1.0                      NaN         NaN        NaN         NaN   

   causaneg3      peso  
0        NaN  1.040102  
1        NaN  0.938927  
2        NaN  0.838407  
3        NaN  0.938927  
4        NaN  1.096378  

[5 rows x 266 columns]

In [9]:
print(df_diputados.columns.tolist())

['Encuestado', 'País', 'legis', 'partido', 'departa', 'tipoelec', 'comision01', 'comision02', 'comision03', 'comision04', 'comision05', 'comision06', 'comision07', 'comision08', 'comision09', 'DEM1', 'PRO101', 'PRO102', 'PRO103', 'PRO104', 'PRO105', 'PRO106', 'PRO107', 'PRO108', 'PRO109', 'PRO110', 'PRO111', 'PRO112', 'PRO113', 'PRO114', 'DEM5', 'DEM6', 'INST101', 'INST102', 'INST103', 'INST104', 'INST105', 'INST106', 'INST107', 'INST108', 'INST109', 'INST110', 'INST111', 'INST112', 'INST113', 'INST114', 'INST115', 'ELE1', 'ELE201', 'IDP101', 'IDP102', 'IDP103', 'IDP104', 'IDP105', 'IDLN101', 'IDLN102', 'IDLN103', 'IDLN104', 'IDLN105', 'IDLN106', 'PP101', 'PP102', 'PP103', 'PP104', 'PP105', 'PP106', 'PP107', 'PP1a01', 'PP1a02', 'DIS1', 'DIS2', 'DIS3', 'REP1', 'REP2', 'CAMP401', 'CAMP402', 'CAMP403', 'CAMP404', 'CAND101', 'MED101', 'MED102', 'MED103', 'MED104', 'CLIEN2a01', 'CLIEN2a02', 'CLIEN2a03', 'CLIEN2a04', 'CLIEN2a05', 'CLIEN4', 'ACT101', 'ACT102', 'ACT103', 'ACT104', 'ACT105', 'V

In [11]:
print(df_diputados[['PRO101', 'PRO102', 'PRO103', 'PRO104', 'PRO105', 'PRO106', 'PRO107', 'PRO108', 'PRO109']]) #Verifico los valores que espero encontrar

     PRO101  PRO102  PRO103  PRO104  PRO105  PRO106  PRO107  PRO108  PRO109
0       8.0     7.0     5.0     8.0     7.0     8.0     7.0     8.0     7.0
1      10.0     9.0     7.0     9.0     7.0    10.0     9.0     7.0    10.0
2      10.0     9.0     7.0     8.0     5.0     7.0     7.0     7.0     9.0
3      10.0    10.0     6.0    10.0     6.0     9.0     6.0     6.0     7.0
4      10.0     3.0     7.0     8.0     9.0    10.0    10.0     6.0    10.0
..      ...     ...     ...     ...     ...     ...     ...     ...     ...
106    10.0     8.0     9.0     7.0     5.0     9.0     9.0    10.0     7.0
107    10.0     8.0     6.0     8.0     1.0    10.0     5.0    10.0    10.0
108    10.0    10.0     8.0    10.0     7.0    10.0     9.0    10.0    10.0
109    10.0     9.0     8.0    10.0     7.0    10.0     7.0     8.0    10.0
110    10.0     8.0    10.0    10.0     7.0    10.0     8.0     9.0     9.0

[110 rows x 9 columns]


In [15]:
#CONF101 es: del 0 al 10 cuanto se puede confiar en la mayoria de la gente, siendo 0 lo minimo y 10 lo maximo.
#ID101: es la autoubicacion en la escala ideologica, siendo 1 izquierda y 10 derecha

#verifico que sus valores esten dentro del rango esperado
print(df_diputados['CONF101'].unique())
print(df_diputados['ID101'].unique())

#asigno columnas a variables
x1 = df_diputados['ID101']
y1 = df_diputados['CONF101']

#añado constante
x1 = sm.add_constant(x1)

#ejecuto el modelo
modelo1 = sm.OLS(y1, x1).fit()
print(modelo1.summary())

[ 7.  4. 10.  5.  6.  9.  3.  8.  2.]
[5. 7. 3. 9. 1. 6. 2. 4. 8.]
                            OLS Regression Results                            
Dep. Variable:                CONF101   R-squared:                       0.049
Model:                            OLS   Adj. R-squared:                  0.041
Method:                 Least Squares   F-statistic:                     5.607
Date:                Thu, 24 Oct 2024   Prob (F-statistic):             0.0197
Time:                        21:46:33   Log-Likelihood:                -210.84
No. Observations:                 110   AIC:                             425.7
Df Residuals:                     108   BIC:                             431.1
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------

In [17]:
#ROES101 es: del 1 al 7 que tan de acuerdo se está con que el sector público, anques que el privado, debe proveer los servicios de salud
#VAL103: del 1 al 10 que tan de acuerdo se está con la legalización del aborto

#verifico que sus valores esten dentro del rango esperado
print(df_diputados['ROES101'].unique())
print(df_diputados['VAL103'].unique())

#elimino valores no deseados
df_diputados = df_diputados.loc[~(df_diputados['VAL103'] == 99)]

#asigno columnas a variables
x2 = df_diputados['ROES101']
y2 = df_diputados['VAL103']

#añado constante
x2 = sm.add_constant(x2)

#ejecuto el modelo
modelo2 = sm.OLS(y2, x2).fit()
print(modelo2.summary())

[2. 1. 7. 4. 3. 5. 6.]
[ 7.  1. 10.  2.  5.  8.  4.  9.  6.  3. 99.]
                            OLS Regression Results                            
Dep. Variable:                 VAL103   R-squared:                       0.093
Model:                            OLS   Adj. R-squared:                  0.084
Method:                 Least Squares   F-statistic:                     10.93
Date:                Thu, 24 Oct 2024   Prob (F-statistic):            0.00129
Time:                        21:46:35   Log-Likelihood:                -285.31
No. Observations:                 109   AIC:                             574.6
Df Residuals:                     107   BIC:                             580.0
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------

In [60]:
#ID101: es la autoubicacion en la escala ideologica, siendo 1 izquierda y 10 derecha
#PRO107: del 1 al 10, que tanto se cree que la corrupcion es un tema importante en la Argentina de hoy

#verifico que sus valores esten dentro del rango esperado
print(df_diputados['ID101'].unique())
print(df_diputados['PRO109'].unique())

#elimino valores no deseados

#asigno columnas a variables
x3 = df_diputados['PRO109']
y3 = df_diputados['ID101']

#añado constante
x3 = sm.add_constant(x3)

#ejecuto el modelo
modelo3 = sm.OLS(y3, x3).fit()
print(modelo3.summary())

[5. 7. 3. 9. 1. 6. 2. 4. 8.]
[ 7. 10.  9.  5.  8.  2.  3.  4.  6.]
                            OLS Regression Results                            
Dep. Variable:                  ID101   R-squared:                       0.235
Model:                            OLS   Adj. R-squared:                  0.227
Method:                 Least Squares   F-statistic:                     32.79
Date:                Thu, 24 Oct 2024   Prob (F-statistic):           9.51e-08
Time:                        21:51:35   Log-Likelihood:                -207.47
No. Observations:                 109   AIC:                             418.9
Df Residuals:                     107   BIC:                             424.3
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------